### ISSUE TITLE
Trying to install torrent-web on VPS and got a lot of errors after npm install -g torrent-web command

### ISSUE THREAD

**Issue by pahager** [mccxiv/torrent-web#7]
Maybe you can help me to solve those errors?  Here are some errors:

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/usr/lib/node_modules/torrent-web/node_modules/bower/lib/node_modules/c       onfigstore/index.js:35:26)
    at Object.Configstore (/usr/lib/node_modules/torrent-web/node_modules/bower/lib/node_m       odules/configstore/index.js:28:44)
    at readCachedConfig (/usr/lib/node_modules/torrent-web/node_modules/bower/lib/config.j       s:19:23)
    at defaultConfig (/usr/lib/node_modules/torrent-web/node_modules/bower/lib/config.js:1       1:12)
    at Object.<anonymous> (/usr/lib/node_modules/torrent-web/node_modules/bower/lib/index.       js:16:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "torrent-web"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! torrent-web@1.1.0 postinstall: `bower install --allow-root`
npm ERR! Exit status 1

Thank you in advance

**Comment by AnasQiblawi** [comment]
you need to install it is using this app
https://git-scm.com/downloads
